### ISSUE TITLE
pytest-xdist not supported

### ISSUE THREAD

**Issue by doerwalter** [christiansandberg/pytest-reporter#3]
I have the following version of Python:

```
Python 3.8.5 (default, Jul 21 2020, 10:48:26)
[Clang 11.0.3 (clang-1103.0.32.62)] on darwin
```

and the following versions of pytest and its plugins

```
pytest                        6.0.1
pytest-forked                 1.3.0
pytest-metadata               1.10.0
pytest-reporter               0.3.0
pytest-reporter-html1         0.6.1
pytest-rerunfailures          9.0
pytest-xdist                  1.34.0
```

Creating the report for the tests in one of my projects fails with the following stacktrace:

```
Traceback (most recent call last):
  File "/Users/walter/pyvenvs/default/bin/pytest", line 10, in <module>
    sys.exit(console_main())
  File "/Users/walter/pyvenvs/default/lib/python3.8/site-packages/_pytest/config/__init__.py", line 180, in console_main
    code = main()
  File "/Users/walter/pyvenvs/default/lib/python3.8/site-packages/_pytest/config/__init__.py", line 157, in main
    ret = config.hook.pytest_cmdline_main(
  File "/Users/walter/pyvenvs/default/lib/python3.8/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/Users/walter/pyvenvs/default/lib/python3.8/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/Users/walter/pyvenvs/default/lib/python3.8/site-packages/pluggy/manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "/Users/walter/pyvenvs/default/lib/python3.8/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/Users/walter/pyvenvs/default/lib/python3.8/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/Users/walter/pyvenvs/default/lib/python3.8/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/Users/walter/pyvenvs/default/lib/python3.8/site-packages/_pytest/main.py", line 289, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "/Users/walter/pyvenvs/default/lib/python3.8/site-packages/_pytest/main.py", line 277, in wrap_session
    config.hook.pytest_sessionfinish(
  File "/Users/walter/pyvenvs/default/lib/python3.8/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/Users/walter/pyvenvs/default/lib/python3.8/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/Users/walter/pyvenvs/default/lib/python3.8/site-packages/pluggy/manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "/Users/walter/pyvenvs/default/lib/python3.8/site-packages/pluggy/callers.py", line 203, in _multicall
    gen.send(outcome)
  File "/Users/walter/pyvenvs/default/lib/python3.8/site-packages/_pytest/terminal.py", line 803, in pytest_sessionfinish
    outcome.get_result()
  File "/Users/walter/pyvenvs/default/lib/python3.8/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/Users/walter/pyvenvs/default/lib/python3.8/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/Users/walter/pyvenvs/default/lib/python3.8/site-packages/pytest_reporter/plugin.py", line 132, in pytest_sessionfinish
    self.config.hook.pytest_reporter_save(config=self.config)
  File "/Users/walter/pyvenvs/default/lib/python3.8/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/Users/walter/pyvenvs/default/lib/python3.8/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/Users/walter/pyvenvs/default/lib/python3.8/site-packages/pluggy/manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "/Users/walter/pyvenvs/default/lib/python3.8/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/Users/walter/pyvenvs/default/lib/python3.8/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/Users/walter/pyvenvs/default/lib/python3.8/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/Users/walter/pyvenvs/default/lib/python3.8/site-packages/pytest_reporter/plugin.py", line 143, in pytest_reporter_save
    content = config.hook.pytest_reporter_render(
  File "/Users/walter/pyvenvs/default/lib/python3.8/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/Users/walter/pyvenvs/default/lib/python3.8/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/Users/walter/pyvenvs/default/lib/python3.8/site-packages/pluggy/manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "/Users/walter/pyvenvs/default/lib/python3.8/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/Users/walter/pyvenvs/default/lib/python3.8/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/Users/walter/pyvenvs/default/lib/python3.8/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/Users/walter/pyvenvs/default/lib/python3.8/site-packages/pytest_reporter_html1/plugin.py", line 173, in pytest_reporter_render
    html = template.render(context)
  File "/Users/walter/pyvenvs/default/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/Users/walter/pyvenvs/default/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/walter/pyvenvs/default/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/walter/pyvenvs/default/lib/python3.8/site-packages/pytest_reporter_html1/templates/html1/index.html", line 1, in top-level template code
    {% extends "html1/base.html" %}
  File "/Users/walter/pyvenvs/default/lib/python3.8/site-packages/pytest_reporter_html1/templates/html1/base.html", line 33, in top-level template code
    {% block content %}{% endblock %}
  File "/Users/walter/pyvenvs/default/lib/python3.8/site-packages/pytest_reporter_html1/templates/html1/index.html", line 5, in block "content"
    {% block summary %}
  File "/Users/walter/pyvenvs/default/lib/python3.8/site-packages/pytest_reporter_html1/templates/html1/index.html", line 50, in block "summary"
    {% include "html1/chart.svg" %}
  File "/Users/walter/pyvenvs/default/lib/python3.8/site-packages/pytest_reporter_html1/templates/html1/chart.svg", line 7, in top-level template code
    {% for category, sub_tests in tests|groupby('status.category') %}
  File "/Users/walter/pyvenvs/default/lib/python3.8/site-packages/jinja2/filters.py", line 987, in do_groupby
    for key, values in groupby(sorted(value, key=expr), expr)
  File "/Users/walter/pyvenvs/default/lib/python3.8/site-packages/jinja2/filters.py", line 74, in attrgetter
    item = environment.getitem(item, part)
  File "/Users/walter/pyvenvs/default/lib/python3.8/site-packages/jinja2/environment.py", line 452, in getitem
    return obj[argument]
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'status'
```

Unfortunately I don't have a simple test case. Reducing the number of tests that are executed makes the bug go away.

**Comment by christiansandberg** [comment]
It seems `pytest_runtest_logstart` and `pytest_runtest_logfinish` hooks were called but not `pytest_runtest_makereport` for some reason. Do you use xdist or forked with these tests? I haven't been able to test those yet.

I made a quick fix which I hope should prevent things from crashing and might shed some light on which tests are causing the problems.

**Comment by doerwalter** [comment]
Yes, I am using `pytest-xdist`. I've installed the current development versions of `pytest-reporter` and `pytest-reporter-html1` (at least I hope I have, via

```bash
git clone https://github.com/christiansandberg/pytest-reporter.git
cd pytest-reporter
git checkout develop
pip install -e .
cd ..
git clone https://github.com/christiansandberg/pytest-reporter-html1.git
cd pytest-reporter-html1
pip install -e .
cd ..
```

Now I get the following exception:
```
Traceback (most recent call last):
  File "/Users/walter/pyvenvs/default/bin/pytest", line 10, in <module>
    sys.exit(console_main())
  File "/Users/walter/pyvenvs/default/lib/python3.8/site-packages/_pytest/config/__init__.py", line 180, in console_main
    code = main()
  File "/Users/walter/pyvenvs/default/lib/python3.8/site-packages/_pytest/config/__init__.py", line 157, in main
    ret = config.hook.pytest_cmdline_main(
  File "/Users/walter/pyvenvs/default/lib/python3.8/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/Users/walter/pyvenvs/default/lib/python3.8/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/Users/walter/pyvenvs/default/lib/python3.8/site-packages/pluggy/manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "/Users/walter/pyvenvs/default/lib/python3.8/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/Users/walter/pyvenvs/default/lib/python3.8/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/Users/walter/pyvenvs/default/lib/python3.8/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/Users/walter/pyvenvs/default/lib/python3.8/site-packages/_pytest/main.py", line 289, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "/Users/walter/pyvenvs/default/lib/python3.8/site-packages/_pytest/main.py", line 277, in wrap_session
    config.hook.pytest_sessionfinish(
  File "/Users/walter/pyvenvs/default/lib/python3.8/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/Users/walter/pyvenvs/default/lib/python3.8/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/Users/walter/pyvenvs/default/lib/python3.8/site-packages/pluggy/manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "/Users/walter/pyvenvs/default/lib/python3.8/site-packages/pluggy/callers.py", line 203, in _multicall
    gen.send(outcome)
  File "/Users/walter/pyvenvs/default/lib/python3.8/site-packages/_pytest/terminal.py", line 803, in pytest_sessionfinish
    outcome.get_result()
  File "/Users/walter/pyvenvs/default/lib/python3.8/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/Users/walter/pyvenvs/default/lib/python3.8/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/Users/walter/x/pytest-reporter/pytest_reporter/plugin.py", line 139, in pytest_sessionfinish
    self.config.hook.pytest_reporter_save(config=self.config)
  File "/Users/walter/pyvenvs/default/lib/python3.8/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/Users/walter/pyvenvs/default/lib/python3.8/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/Users/walter/pyvenvs/default/lib/python3.8/site-packages/pluggy/manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "/Users/walter/pyvenvs/default/lib/python3.8/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/Users/walter/pyvenvs/default/lib/python3.8/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/Users/walter/pyvenvs/default/lib/python3.8/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/Users/walter/x/pytest-reporter/pytest_reporter/plugin.py", line 150, in pytest_reporter_save
    content = config.hook.pytest_reporter_render(
  File "/Users/walter/pyvenvs/default/lib/python3.8/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/Users/walter/pyvenvs/default/lib/python3.8/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/Users/walter/pyvenvs/default/lib/python3.8/site-packages/pluggy/manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "/Users/walter/pyvenvs/default/lib/python3.8/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/Users/walter/pyvenvs/default/lib/python3.8/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/Users/walter/pyvenvs/default/lib/python3.8/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/Users/walter/x/pytest-reporter-html1/pytest_reporter_html1/plugin.py", line 173, in pytest_reporter_render
    html = template.render(context)
  File "/Users/walter/pyvenvs/default/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/Users/walter/pyvenvs/default/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/walter/pyvenvs/default/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/walter/x/pytest-reporter-html1/pytest_reporter_html1/templates/html1/index.html", line 1, in top-level template code
    {% extends "html1/base.html" %}
  File "/Users/walter/x/pytest-reporter-html1/pytest_reporter_html1/templates/html1/base.html", line 32, in top-level template code
    {% block content %}{% endblock %}
  File "/Users/walter/x/pytest-reporter-html1/pytest_reporter_html1/templates/html1/index.html", line 78, in block "content"
    {% for fspath, tests in tests|groupby('item.fspath') %}
  File "/Users/walter/pyvenvs/default/lib/python3.8/site-packages/jinja2/filters.py", line 987, in do_groupby
    for key, values in groupby(sorted(value, key=expr), expr)
jinja2.exceptions.UndefinedError: 'None' has no attribute 'fspath'
```

The call looked like this:

```
pytest -v -l -n10 -k 'misc or sgmlop' --template=html1/index.html --report=report.html
```

**Comment by christiansandberg** [comment]
I've been assuming the hooks are called in a specific order as specified by the [pytest documentation](https://docs.pytest.org/en/stable/reference.html#pytest.hookspec.pytest_runtest_protocol), but it seems that might not be valid in some cases...

**Comment by doerwalter** [comment]
This might be a problem of `pytest-xdist` Running the tests without `-n10` works (but takes 1.5 hours).

**Comment by christiansandberg** [comment]
I need to do some experimentation with xdist and see if I can reproduce it.

**Comment by christiansandberg** [comment]
Looking at the xdist code and doing some testing it seems hooks are called differently than a normal Pytest session, for logical reasons though since tests are executed in isolated workers. I need some more time to restructure things and some information may not even be available in an xdist session which templates may need to be aware of.

**Comment by christiansandberg** [comment]
I've made new releases which I would be happy if you could try out!

**Comment by doerwalter** [comment]
With `pytest-reporter` 0.4.0 and `pytest-reporter-html1` 0.7.0 now `-n10` seems to work without any problems. Thanks!
